repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0  # Use the latest stable version of Black
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 8.0.0
    hooks:
      - id: isort

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2  # Use the latest stable version of autopep8
    hooks:
      - id: autopep8
